FROM python:3.11-slim
WORKDIR /app

COPY serve/serve.py /app/app.py

RUN pip install --no-cache-dir \
    pandas \
    scikit-learn==1.3.1 \
    mlflow==2.7.1 \
    flask \
    gunicorn \
    boto3 \
    psutil==7.1.0

ENV MODEL_NAME=trip_duration MODEL_STAGE=staging
EXPOSE 9696
