FROM python:3.11-slim
RUN pip install --no-cache-dir mlflow==2.7.1
CMD ["bash","-lc","mlflow ui --host 0.0.0.0 --port 5000 \
  --backend-store-uri sqlite:////mlflow/mlflow.db \
  --default-artifact-root file:///mlflow/artifacts"]
