FROM python:3.11-slim
WORKDIR /app

# if your API file is named differently, adjust COPY and gunicorn command
COPY serve/serve.py /app/app.py

# include pandas (and mlflow, flask, gunicorn, sklearn)
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn==1.3.1 \
    mlflow==2.7.1 \
    flask \
    gunicorn \
    boto3

ENV MODEL_NAME=trip_duration MODEL_STAGE=staging
EXPOSE 9696
